# Generated by Django 2.2.14 on 2021-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andra Pradesh', 'Andra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('U.P', 'U.P'), ('M.P', 'M.P'), ('Delhi', 'Delhi'), ('Maharastra', 'Maharastra'), ('Madhya Pradesh', 'Madhya Pradesh')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('T', 'Tablet'), ('KW', 'Kids Wear'), ('G', 'Grocerries'), ('TG', 'Toys & Games Store')], max_length=2),
        ),
    ]
