# Generated by Django 2.2.14 on 2021-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210503_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('T', 'Tablet'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('C', 'Camera'), ('TV', 'TV'), ('PC', 'PC'), ('SW', 'Smart Wearable Tech'), ('HC', 'Health Care Appliances'), ('CP', 'Computer Peripherals'), ('KC', 'Kids Clothing'), ('KF', 'Kids Footwear'), ('TO', 'Toys'), ('BC', 'Baby Care'), ('SS', 'School Supplies'), ('G', 'Grocerries'), ('TG', 'Toys & Games Store'), ('MW', 'Mens Wear'), ('WW', 'Womens Wear'), ('G', 'Goggles'), ('W', 'Watches'), ('HB', 'HandBag and Clutches'), ('S', 'Shoes and Sandals'), ('SF', 'Snack Food'), ('TC', 'Tea , Coffee and Beverages'), ('SM', 'Spices and Masala'), ('DF', 'Dried Fruits and Nuts'), ('CM', 'Cerial and Muesli')], max_length=2),
        ),
    ]
