# Generated by Django 2.2.14 on 2021-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210509_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='transaction_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
