# Generated by Django 2.2.14 on 2021-05-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210514_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_available',
        ),
    ]
