# Generated by Django 2.2.14 on 2021-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210514_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=100),
        ),
    ]
