# Generated by Django 2.2.14 on 2021-05-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=True),
        ),
    ]
