# Generated by Django 2.2.14 on 2021-05-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210516_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmDataBase',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('checksumhash', models.CharField(max_length=255)),
                ('txn_id', models.CharField(max_length=100)),
            ],
        ),
    ]
