# Generated by Django 2.2.14 on 2021-05-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_paytmdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmdatabase',
            name='banktxnid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paytmdatabase',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paytmdatabase',
            name='txndate',
            field=models.CharField(default=20, max_length=255),
            preserve_default=False,
        ),
    ]
