# Generated by Django 2.2.14 on 2021-05-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210517_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmdatabase',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
