# Generated by Django 2.2.14 on 2021-05-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_paytmdatabase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmdatabase',
            name='user',
        ),
    ]
