# Generated by Django 2.2.14 on 2021-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_paytmdatabase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
